version: "3"

services:

  d3-pandas:
    image: d3-pandas
    build:
      context: ./src
      dockerfile: ./Dockerfile
    env_file: ./src/pandas.env
    volumes:
      - ${PWD}/src:/app
    tty: true

